use anyhow::{Context, Result, bail};
use chrono::{DateTime, TimeZone, Utc};
use std::collections::HashMap;

/// Parsed results from a DLMS/AXDR-like binary payload
#[derive(Debug, Clone)]
pub struct DlmsBinaryFrame {
    pub manufacturer_id: String,
    pub logical_device_name: String,
    pub timestamp: DateTime<Utc>,
    
    // Extracted values
    pub active_energy_import_wh: Option<u64>,
    pub active_energy_export_wh: Option<u64>,
    pub voltage_cv: Option<u32>,        // centi-volts (100th of V)
    pub current_ma: Option<u32>,        // milli-amps
    pub battery_soc_bps: Option<u32>,   // basis points (100th of a percent)
}

impl DlmsBinaryFrame {
    /// Parses the custom binary format generated by the Smart Meter Simulator
    /// 
    /// Format:
    /// [Header: Manuf ID (3 bytes) + LDN (8 bytes padded)]
    /// [Timestamp: u64 big endian (8 bytes)]
    /// [List of: OBIS_INDEX (1 byte) + VALUE (4 or 8 bytes big endian)]
    pub fn parse(payload: &[u8]) -> Result<Self> {
        let mut cursor = 0;
        let len = payload.len();

        // 1. Header (11 bytes total: 3 bytes manufacturer + 8 bytes LDN)
        if len < 19 {
            bail!("Payload too small ({} bytes) to contain standard header and timestamp", len);
        }

        let manufacturer_id = String::from_utf8_lossy(&payload[cursor..cursor + 3]).to_string();
        cursor += 3;

        // Parse LDN and strip trailing null bytes
        let mut ldn_bytes = &payload[cursor..cursor + 8];
        if let Some(pos) = ldn_bytes.iter().position(|&b| b == 0) {
            ldn_bytes = &ldn_bytes[..pos];
        }
        let logical_device_name = String::from_utf8_lossy(ldn_bytes).to_string();
        cursor += 8;

        // 2. Timestamp (8 bytes big endian)
        let ts_bytes: [u8; 8] = payload[cursor..cursor + 8].try_into().unwrap();
        let ts_seconds = u64::from_be_bytes(ts_bytes);
        let timestamp = Utc.timestamp_opt(ts_seconds as i64, 0)
            .single()
            .context("Invalid timestamp inside binary payload")?;
        cursor += 8;

        let mut frame = DlmsBinaryFrame {
            manufacturer_id,
            logical_device_name,
            timestamp,
            active_energy_import_wh: None,
            active_energy_export_wh: None,
            voltage_cv: None,
            current_ma: None,
            battery_soc_bps: None,
        };

        // 3. OBIS Coded Values
        while cursor < len {
            let index = payload[cursor];
            cursor += 1;

            match index {
                1 => { // ACTIVE_ENERGY_IMPORT (8 bytes)
                    if cursor + 8 > len { break; }
                    let val_bytes: [u8; 8] = payload[cursor..cursor + 8].try_into().unwrap();
                    frame.active_energy_import_wh = Some(u64::from_be_bytes(val_bytes));
                    cursor += 8;
                }
                2 => { // ACTIVE_ENERGY_EXPORT (8 bytes)
                    if cursor + 8 > len { break; }
                    let val_bytes: [u8; 8] = payload[cursor..cursor + 8].try_into().unwrap();
                    frame.active_energy_export_wh = Some(u64::from_be_bytes(val_bytes));
                    cursor += 8;
                }
                3 => { // VOLTAGE_L1 (4 bytes)
                    if cursor + 4 > len { break; }
                    let val_bytes: [u8; 4] = payload[cursor..cursor + 4].try_into().unwrap();
                    frame.voltage_cv = Some(u32::from_be_bytes(val_bytes));
                    cursor += 4;
                }
                4 => { // CURRENT_L1 (4 bytes)
                    if cursor + 4 > len { break; }
                    let val_bytes: [u8; 4] = payload[cursor..cursor + 4].try_into().unwrap();
                    frame.current_ma = Some(u32::from_be_bytes(val_bytes));
                    cursor += 4;
                }
                5 => { // BATTERY_SOC (4 bytes)
                    if cursor + 4 > len { break; }
                    let val_bytes: [u8; 4] = payload[cursor..cursor + 4].try_into().unwrap();
                    frame.battery_soc_bps = Some(u32::from_be_bytes(val_bytes));
                    cursor += 4;
                }
                _ => {
                    // Unknown OBIS code. Since values are variable length in our simplified model 
                    // and we don't have TLV strictly encoded for unknown tags, 
                    // we cannot safely advance the cursor. Stop parsing.
                    tracing::warn!("Unknown OBIS index {} encountered during binary decode, halting parsing for remaining blocks.", index);
                    break;
                }
            }
        }

        Ok(frame)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_binary_frame() {
        let mut payload = Vec::new();
        // Manufacturer (3 bytes)
        payload.extend_from_slice(b"INC");
        // LDN (8 bytes padded)
        payload.extend_from_slice(b"DEVICE1\0");
        // Timestamp (8 bytes)
        let ts_sec: u64 = 1700000000;
        payload.extend_from_slice(&ts_sec.to_be_bytes());
        
        // 1: Import Wh (5000 Wh) -> 8 bytes
        payload.push(1);
        payload.extend_from_slice(&5000_u64.to_be_bytes());
        
        // 3: Voltage (230.50 V -> 23050 cV) -> 4 bytes
        payload.push(3);
        payload.extend_from_slice(&23050_u32.to_be_bytes());

        let frame = DlmsBinaryFrame::parse(&payload).unwrap();
        assert_eq!(frame.manufacturer_id, "INC");
        assert_eq!(frame.logical_device_name, "DEVICE1");
        assert_eq!(frame.timestamp.timestamp(), 1700000000);
        assert_eq!(frame.active_energy_import_wh, Some(5000));
        assert_eq!(frame.active_energy_export_wh, None);
        assert_eq!(frame.voltage_cv, Some(23050));
    }
}
