//! Generated ConnectRPC / Buffa protocol types for the Aggregator Bridge.
//!
//! Each submodule pulls in code generated by `build.rs` (via `connectrpc_build`)
//! and flattens the package path so callers can use the top-level re-exports:
//!   - `aggregator_protocol::oracle::*`   (proto package `gridtokenx.oracle.v1`)
//!   - `aggregator_protocol::dispatch::*` (proto package `gridtokenx.dispatch`)
//!   - `aggregator_protocol::identity::*` (proto package `identity`)

pub mod oracle {
    include!(concat!(env!("OUT_DIR"), "/_oracle_include.rs"));
    pub use gridtokenx::oracle::v1::*;
}

pub mod dispatch {
    include!(concat!(env!("OUT_DIR"), "/_dispatch_include.rs"));
    pub use gridtokenx::dispatch::*;
}

pub mod identity {
    include!(concat!(env!("OUT_DIR"), "/_identity_include.rs"));
    pub use identity::*;
}
