//! Generated ConnectRPC / Buffa protocol types for the Aggregator Bridge.
//!
//! Each submodule pulls in code generated by `build.rs` (via `connectrpc_build`)
//! and flattens the package path so callers can use the top-level re-exports:
//!   - `aggregator_protocol::oracle::*`   (proto package `gridtokenx.oracle.v1`)
//!   - `aggregator_protocol::dispatch::*` (proto package `gridtokenx.dispatch`)
//!   - `aggregator_protocol::identity::*` (proto package `identity`)

// The generated prost/connectrpc code nests modules matching the proto package
// path (e.g. `oracle::gridtokenx::oracle`), which trips `clippy::module_inception`
// on machine-generated code we don't hand-edit. Allow it crate-wide.
#![allow(clippy::module_inception)]

pub mod oracle {
    include!(concat!(env!("OUT_DIR"), "/_oracle_include.rs"));
    pub use gridtokenx::oracle::v1::*;
}

pub mod dispatch {
    include!(concat!(env!("OUT_DIR"), "/_dispatch_include.rs"));
    pub use gridtokenx::dispatch::*;
}

pub mod identity {
    include!(concat!(env!("OUT_DIR"), "/_identity_include.rs"));
    pub use identity::*;
}
